baseurl: /
title: 城市群生态基底核算与健康诊断
languageCode: zh-cn
DefaultContentLanguage: zh-cn
paginate: '10'
theme: hugo-dpsg
Author:
  avatar: img/avatar.png
  bio: 南京大学研究团队致力于高分辨率时空数据库与动态可视化平台构建。
  name: 南京大学研究团队
Params:
  authorbox: yes
  copyright: DGSP local group
  dateformat: 02.01.2006
  description: Welcome to our scout group!
  footer:
    right: Donate!
    text: '[Imprint and Privacy](/imprint)'
  indexPager: yes
  logo:
    header: img/header2.jpg
    image: img/placeholder2.png
    subtitle: 综合数据资源中心及动态一体化评价与监管系统
    title: 城市群生态基底核算与健康诊断
  mainSections:
    - post
    - blog
    - news
  opengraph: yes
  pager: yes
  post_meta:
    - author
    - date
    - categories
    - translations
  readmore: no
  schema: yes
  sidebar:
    home: right
    list: left
    single: no
    widgets:
      - search
      - recent
      - categories
      - taglist
      - social
      - languages
  style:
    vars:
      highlightColor: '#003056'
  toc: yes
  twitter_cards: yes
  widgets:
    recent_num: 5
    tags_counter: no
menu:
  main:
    - identifier: start
      name: 平台首页
      url: /
      weight: 1
    - identifier: database
      name: 综合数据资源中心
      url: /database/
      weight: 2
    - identifier: methods
      name: 动态一体化评价与监管系统
      url: /methods/
      weight: 3
    - identifier: about
      name: 课题简介
      url: /about/
      weight: 4
