baseurl: /
title: 城市群生态基底核算与健康诊断
languageCode: zh-cn
DefaultContentLanguage: zh-cn
paginate: '10'
theme: hugo-dpsg
Author:
  avatar: img/avatar.png
  bio: 课题组研究团队致力于珠三角城市群生态基底核算与健康诊断研究。
  name: 课题组研究团队
Params:
  authorbox: yes
  copyright: 南京大学研究团队
  dateformat: 2006年1月2日
  description: 欢迎访问！
  footer:
    right: Donate!
    text: '[Imprint and Privacy](/imprint)'
  indexPager: yes
  logo:
    header: img/header2.jpg
    image: img/placeholder2.png
    subtitle: 综合数据资源中心及动态一体化评价与监管系统
    title: 城市群生态基底核算与健康诊断
  mainSections:
    - post
    - blog
    - news
  opengraph: yes
  pager: yes
  post_meta:
    - author
    - date
    - categories
    - translations
  readmore: no
  schema: yes
  sidebar:
    home: right
    list: left
    single: no
    widgets:
      - search
      - recent
      - categories
      - taglist
      - social
      - languages
  style:
    vars:
      highlightColor: '#003056'
  toc: yes
  twitter_cards: yes
  widgets:
    recent_num: 5
    tags_counter: no
menu:
  main:
    - identifier: start
      name: 首页
      url: /
      weight: 1
    - identifier: about
      name: 课题简介
      url: /about/
      weight: 2
    - identifier: database
      name: 数据库
      url: /database/
      weight: 3
    - identifier: methods
      name: 方法库
      url: /methods/
      weight: 4
    - identifier: complex
      name: 复杂性分析
      url: /complex/
      weight: 5
    - identifier: account
      name: 基底核算
      url: /account/
      weight: 6
    - identifier: diagnose
      name: 健康诊断
      url: /diagnose/
      weight: 7
    - identifier: optimize
      name: 优化调控
      url: /optimize/
      weight: 8
    - identifier: alert
      name: 诊断预警
      url: /alert/
      weight: 9
    - identifier: platform
      name: 监管平台
      url: /platform/
      weight: 10
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
